[ziwooda] Assignment of week 2
AUSG/2023-tech-interview-study pull request #10
Opened 2023-02-19 17:29 UTC by ziwooda

2주차 목표 [ 02.18 - 02.23 ]
1. 공통과제
- [ ] [21758 꿀따기](https://www.acmicpc.net/problem/21758)
- [ ] [2141 우체국](https://www.acmicpc.net/problem/2141)
<br>      

2. 개인과제
- [ ] [algo] graph
- [ ] [algo] binary search
- [ ] [code] 최소 2문제

2023-02-24 07:52 UTC, ziwooda commented
1. 알고리즘 - 그래프(BFS/DFS), 이진탐색 정리
2. 코딩테스트 - (공통과제) BOJ2141, BOJ21758, (개인과제)BOJ20444
    1. BOJ21759 Runtime Error 해결 필요

2023-02-24 09:02 UTC, AllyHyeseongKim commented
고생 많으셨습니다! 질문은 없습니다😊

2023-02-24 09:02 UTC, AllyHyeseongKim approved these changes
고생 많으셨습니다! 질문은 없습니다😊

2023-02-24 09:05 UTC, AllyHyeseongKim requested changes
고생 많으셨습니다! 질문은 없습니다😊
`README.md`에 목표 수정 부탁드려요~

2023-02-24 11:28 UTC, qjatjr29 approved these changes
고생하셨습니다 🙂

2023-02-25 05:20 UTC, AllyHyeseongKim approved these changes

2023-02-25 05:21 UTC, merged